server:
  port: 9572

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: payment
          uri: lb://HYSTRIX-PAYMENT-SERVICE
          predicates:
              - Path=/payment/getOK/{id},/payment/getTimeOut/{id}/{timeout}
        - id: order
          uri: lb://HYSTRIX-FEIGN-ORDER-SERVICE
          predicates:
              - Path=/order/payment/getOK/{id},/order/payment/getTimeOut/{id}/{timeout}
eureka:
  client:
    register-with-eureka: true    #标识向注册中心注册自己
    fetch-registry: true
    service-url:
      #defaultZone: http://demo:123abc@eureka7001.com:7001/eureka,http://demo:123abc@eureka7002.com:7002/eureka
      defaultZone: http://demo:123abc@eureka7001.com:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true